info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: 用来测试 API 是否正常
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: 用来测试 API 是否正常
swagger: "2.0"
